# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_storage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('raw_email_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_storage.FileReference')),
                ('recipients', models.ManyToManyField(related_name='recipients', to='email.EmailAddress')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='email.EmailAddress')),
            ],
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email.EmailMessage'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='file_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_storage.FileReference'),
        ),
    ]
