# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1024)),
                ('path', models.TextField()),
                ('mime_type', models.CharField(max_length=128)),
                ('storage_engine', models.CharField(max_length=32)),
                ('status_changes', models.ManyToManyField(to='shared.DataUpdate')),
            ],
        ),
    ]
